### PR TITLE
feat(ipc): add perform note and ensemble

### PR DESCRIPTION
**Pull request by FairyScript**

### CODE REVIEW

**Comment by zhyupe** [comment]
Is the opcode for 5.1 or 5.11? They are different and it's unlikely that you discovered an opcode for 5.1 now ...

**Comment by FairyScript** [comment]
it's 5.1
Considering that the major version of thid repo is not updated,I push the older version to avoid conflict.

**Comment by zhyupe** [comment]
Sorry that I forgot to commit the opcodes for 5.11. I've pushed them and you can set them as 5.11_cn.

**Comment by FairyScript** [comment]
I edited my PR. Now the opcodes are updated.

**Pull request merged**
